[theme]
#font = "" #changing the font style whenever streamlit includes that feature

#Primary accent for interactive elements
primaryColor = "#7792E3"

#Background colour for the main content area #273346
backgroundColor = "beige"

#Background color for side bar and most interative widgets #B9F1C0
secondaryBackgroundColor = "beige"

#Color used for almost all text
textColor = "navyblue"

#Font family for all text in the app except code blocks
#Accepted values (sans serif | serif | monospace)
#Default: "sans serif";


